version: '3'
services:

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypass"
    ports:
      - '5432:5432'

  backend:
    build: .
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres-db:
    driver: local