spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: myuser
    password: mypass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

file:
  storage:
    path: /Users/uliamaslova/Desktop/save file


server:
  port: 8080
